#!/bin/sh


echo "removing stale config files"
touch .deps
rm -f aclocal.m4
rm -f generated_lists
rm -rf autom4te*.cache

echo "checking buildconf prereqs";
perl build/version_check.pl libtool   || exit 1
perl build/version_check.pl autoconf  || exit 1
perl build/version_check.pl automake  || exit 1

libtool="libtoolize --automake --copy --force"
echo "running $libtool" && $libtool && \
echo "running aclocal"  && aclocal && \
echo "running autoconf" && autoconf && \
echo "running autoheader" && autoheader && \
echo "running automake -a -c" && automake -a -c && \
echo "buildconf successful."
