APXS = /maz/dougm/apache/bin/apxs

PERL = perl

MY_CFLAGS = `$(PERL) -MApache::libapreq -e ccopts`
MY_LDFLAGS = `$(PERL) -MApache::libapreq -e ldopts`

SRC = mod_testapreq.c

libtestapreq.so: $(SRC)
	LD_RUN_PATH=$(LD_RUN_PATH) $(APXS) -c -o $@ $(MY_CFLAGS) $(MY_LDFLAGS) $(SRC)

